services:
  executor:
    user: root

    entrypoint:
      - sh
      - -c

    command:
      - >
        pip install debugpy &&
        python -m debugpy
        --listen 0.0.0.0:5678
        --wait-for-client
        -m services.executor.main

    ports:
      - "5678:5678"